title: "Raul de Queiroz Mendes"
logo: /assets/Queiroz_Mendes.jpg
description: "Computer Vision Engineer | Machine Learning Specialist | Roboticist"
theme: jekyll-theme-minimal
url: "https://raulqm.github.io"

author:
  name: "Raul de Queiroz Mendes"
  email: "r.de.queiroz.mendes@tue.nl"

social_links:
  linkedin: "https://www.linkedin.com/in/raul-de-queiroz-mendes-2272a814b/"
  github: "https://github.com/RaulQM"
  orcid: "https://orcid.org/0000-0003-3866-9749"

show_downloads: false
google_analytics: false

markdown: kramdown
include: ["assets/css"]

