title: "Raul de Queiroz Mendes"
email: "r.de.queiroz.mendes@tue.nl"
description: "Computer Vision Engineer | Machine Learning Specialist | Roboticist"
url: "https://raulqm.github.io"
author:
  name: "Raul de Queiroz Mendes"
  linkedin: "https://www.linkedin.com/in/raul-de-queiroz-mendes-2272a814b/"
  github: "https://github.com/RaulQM"
  orcid: "https://orcid.org/0000-0003-3866-9749"

